// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Diseasetype is the predicate function for diseasetype builders.
type Diseasetype func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Severity is the predicate function for severity builders.
type Severity func(*sql.Selector)
