// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/KOB4k/app/ent/disease"
	"github.com/KOB4k/app/ent/diseasetype"
	"github.com/KOB4k/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DiseaseTypeQuery is the builder for querying DiseaseType entities.
type DiseaseTypeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.DiseaseType
	// eager-loading edges.
	withDisease *DiseaseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (dtq *DiseaseTypeQuery) Where(ps ...predicate.DiseaseType) *DiseaseTypeQuery {
	dtq.predicates = append(dtq.predicates, ps...)
	return dtq
}

// Limit adds a limit step to the query.
func (dtq *DiseaseTypeQuery) Limit(limit int) *DiseaseTypeQuery {
	dtq.limit = &limit
	return dtq
}

// Offset adds an offset step to the query.
func (dtq *DiseaseTypeQuery) Offset(offset int) *DiseaseTypeQuery {
	dtq.offset = &offset
	return dtq
}

// Order adds an order step to the query.
func (dtq *DiseaseTypeQuery) Order(o ...OrderFunc) *DiseaseTypeQuery {
	dtq.order = append(dtq.order, o...)
	return dtq
}

// QueryDisease chains the current query on the disease edge.
func (dtq *DiseaseTypeQuery) QueryDisease() *DiseaseQuery {
	query := &DiseaseQuery{config: dtq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(diseasetype.Table, diseasetype.FieldID, dtq.sqlQuery()),
			sqlgraph.To(disease.Table, disease.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, diseasetype.DiseaseTable, diseasetype.DiseaseColumn),
		)
		fromU = sqlgraph.SetNeighbors(dtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DiseaseType entity in the query. Returns *NotFoundError when no diseasetype was found.
func (dtq *DiseaseTypeQuery) First(ctx context.Context) (*DiseaseType, error) {
	dts, err := dtq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(dts) == 0 {
		return nil, &NotFoundError{diseasetype.Label}
	}
	return dts[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) FirstX(ctx context.Context) *DiseaseType {
	dt, err := dtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return dt
}

// FirstID returns the first DiseaseType id in the query. Returns *NotFoundError when no id was found.
func (dtq *DiseaseTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dtq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{diseasetype.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) FirstXID(ctx context.Context) int {
	id, err := dtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only DiseaseType entity in the query, returns an error if not exactly one entity was returned.
func (dtq *DiseaseTypeQuery) Only(ctx context.Context) (*DiseaseType, error) {
	dts, err := dtq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(dts) {
	case 1:
		return dts[0], nil
	case 0:
		return nil, &NotFoundError{diseasetype.Label}
	default:
		return nil, &NotSingularError{diseasetype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) OnlyX(ctx context.Context) *DiseaseType {
	dt, err := dtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return dt
}

// OnlyID returns the only DiseaseType id in the query, returns an error if not exactly one id was returned.
func (dtq *DiseaseTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dtq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = &NotSingularError{diseasetype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := dtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DiseaseTypes.
func (dtq *DiseaseTypeQuery) All(ctx context.Context) ([]*DiseaseType, error) {
	if err := dtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dtq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) AllX(ctx context.Context) []*DiseaseType {
	dts, err := dtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return dts
}

// IDs executes the query and returns a list of DiseaseType ids.
func (dtq *DiseaseTypeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := dtq.Select(diseasetype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := dtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dtq *DiseaseTypeQuery) Count(ctx context.Context) (int, error) {
	if err := dtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dtq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) CountX(ctx context.Context) int {
	count, err := dtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dtq *DiseaseTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := dtq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dtq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dtq *DiseaseTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := dtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dtq *DiseaseTypeQuery) Clone() *DiseaseTypeQuery {
	return &DiseaseTypeQuery{
		config:     dtq.config,
		limit:      dtq.limit,
		offset:     dtq.offset,
		order:      append([]OrderFunc{}, dtq.order...),
		unique:     append([]string{}, dtq.unique...),
		predicates: append([]predicate.DiseaseType{}, dtq.predicates...),
		// clone intermediate query.
		sql:  dtq.sql.Clone(),
		path: dtq.path,
	}
}

//  WithDisease tells the query-builder to eager-loads the nodes that are connected to
// the "disease" edge. The optional arguments used to configure the query builder of the edge.
func (dtq *DiseaseTypeQuery) WithDisease(opts ...func(*DiseaseQuery)) *DiseaseTypeQuery {
	query := &DiseaseQuery{config: dtq.config}
	for _, opt := range opts {
		opt(query)
	}
	dtq.withDisease = query
	return dtq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DiseaseType.Query().
//		GroupBy(diseasetype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (dtq *DiseaseTypeQuery) GroupBy(field string, fields ...string) *DiseaseTypeGroupBy {
	group := &DiseaseTypeGroupBy{config: dtq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dtq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.DiseaseType.Query().
//		Select(diseasetype.FieldName).
//		Scan(ctx, &v)
//
func (dtq *DiseaseTypeQuery) Select(field string, fields ...string) *DiseaseTypeSelect {
	selector := &DiseaseTypeSelect{config: dtq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dtq.sqlQuery(), nil
	}
	return selector
}

func (dtq *DiseaseTypeQuery) prepareQuery(ctx context.Context) error {
	if dtq.path != nil {
		prev, err := dtq.path(ctx)
		if err != nil {
			return err
		}
		dtq.sql = prev
	}
	return nil
}

func (dtq *DiseaseTypeQuery) sqlAll(ctx context.Context) ([]*DiseaseType, error) {
	var (
		nodes       = []*DiseaseType{}
		_spec       = dtq.querySpec()
		loadedTypes = [1]bool{
			dtq.withDisease != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &DiseaseType{config: dtq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, dtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := dtq.withDisease; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*DiseaseType)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Disease(func(s *sql.Selector) {
			s.Where(sql.InValues(diseasetype.DiseaseColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.disease_type_disease
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "disease_type_disease" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "disease_type_disease" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Disease = append(node.Edges.Disease, n)
		}
	}

	return nodes, nil
}

func (dtq *DiseaseTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dtq.querySpec()
	return sqlgraph.CountNodes(ctx, dtq.driver, _spec)
}

func (dtq *DiseaseTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dtq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (dtq *DiseaseTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   diseasetype.Table,
			Columns: diseasetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: diseasetype.FieldID,
			},
		},
		From:   dtq.sql,
		Unique: true,
	}
	if ps := dtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dtq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dtq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dtq *DiseaseTypeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(dtq.driver.Dialect())
	t1 := builder.Table(diseasetype.Table)
	selector := builder.Select(t1.Columns(diseasetype.Columns...)...).From(t1)
	if dtq.sql != nil {
		selector = dtq.sql
		selector.Select(selector.Columns(diseasetype.Columns...)...)
	}
	for _, p := range dtq.predicates {
		p(selector)
	}
	for _, p := range dtq.order {
		p(selector)
	}
	if offset := dtq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dtq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DiseaseTypeGroupBy is the builder for group-by DiseaseType entities.
type DiseaseTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dtgb *DiseaseTypeGroupBy) Aggregate(fns ...AggregateFunc) *DiseaseTypeGroupBy {
	dtgb.fns = append(dtgb.fns, fns...)
	return dtgb
}

// Scan applies the group-by query and scan the result into the given value.
func (dtgb *DiseaseTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dtgb.path(ctx)
	if err != nil {
		return err
	}
	dtgb.sql = query
	return dtgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := dtgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(dtgb.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := dtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := dtgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dtgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) StringX(ctx context.Context) string {
	v, err := dtgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(dtgb.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := dtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := dtgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dtgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) IntX(ctx context.Context) int {
	v, err := dtgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(dtgb.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := dtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := dtgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dtgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := dtgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(dtgb.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := dtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := dtgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (dtgb *DiseaseTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dtgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dtgb *DiseaseTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := dtgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dtgb *DiseaseTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dtgb.sqlQuery().Query()
	if err := dtgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dtgb *DiseaseTypeGroupBy) sqlQuery() *sql.Selector {
	selector := dtgb.sql
	columns := make([]string, 0, len(dtgb.fields)+len(dtgb.fns))
	columns = append(columns, dtgb.fields...)
	for _, fn := range dtgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(dtgb.fields...)
}

// DiseaseTypeSelect is the builder for select fields of DiseaseType entities.
type DiseaseTypeSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (dts *DiseaseTypeSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := dts.path(ctx)
	if err != nil {
		return err
	}
	dts.sql = query
	return dts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dts *DiseaseTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := dts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(dts.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := dts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dts *DiseaseTypeSelect) StringsX(ctx context.Context) []string {
	v, err := dts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dts *DiseaseTypeSelect) StringX(ctx context.Context) string {
	v, err := dts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(dts.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := dts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dts *DiseaseTypeSelect) IntsX(ctx context.Context) []int {
	v, err := dts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dts *DiseaseTypeSelect) IntX(ctx context.Context) int {
	v, err := dts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(dts.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := dts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dts *DiseaseTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := dts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dts *DiseaseTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := dts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(dts.fields) > 1 {
		return nil, errors.New("ent: DiseaseTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := dts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dts *DiseaseTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := dts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (dts *DiseaseTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{diseasetype.Label}
	default:
		err = fmt.Errorf("ent: DiseaseTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dts *DiseaseTypeSelect) BoolX(ctx context.Context) bool {
	v, err := dts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dts *DiseaseTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dts.sqlQuery().Query()
	if err := dts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dts *DiseaseTypeSelect) sqlQuery() sql.Querier {
	selector := dts.sql
	selector.Select(selector.Columns(dts.fields...)...)
	return selector
}
