// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/KOB4k/app/ent/diseasetype"
	"github.com/KOB4k/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DiseaseTypeDelete is the builder for deleting a DiseaseType entity.
type DiseaseTypeDelete struct {
	config
	hooks      []Hook
	mutation   *DiseaseTypeMutation
	predicates []predicate.DiseaseType
}

// Where adds a new predicate to the delete builder.
func (dtd *DiseaseTypeDelete) Where(ps ...predicate.DiseaseType) *DiseaseTypeDelete {
	dtd.predicates = append(dtd.predicates, ps...)
	return dtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dtd *DiseaseTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dtd.hooks) == 0 {
		affected, err = dtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiseaseTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dtd.mutation = mutation
			affected, err = dtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dtd.hooks) - 1; i >= 0; i-- {
			mut = dtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtd *DiseaseTypeDelete) ExecX(ctx context.Context) int {
	n, err := dtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dtd *DiseaseTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: diseasetype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: diseasetype.FieldID,
			},
		},
	}
	if ps := dtd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dtd.driver, _spec)
}

// DiseaseTypeDeleteOne is the builder for deleting a single DiseaseType entity.
type DiseaseTypeDeleteOne struct {
	dtd *DiseaseTypeDelete
}

// Exec executes the deletion query.
func (dtdo *DiseaseTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := dtdo.dtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{diseasetype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dtdo *DiseaseTypeDeleteOne) ExecX(ctx context.Context) {
	dtdo.dtd.ExecX(ctx)
}
