// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/KOB4k/app/ent/diseasetype"
	"github.com/facebookincubator/ent/dialect/sql"
)

// DiseaseType is the model entity for the DiseaseType schema.
type DiseaseType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiseaseTypeQuery when eager-loading is set.
	Edges DiseaseTypeEdges `json:"edges"`
}

// DiseaseTypeEdges holds the relations/edges for other nodes in the graph.
type DiseaseTypeEdges struct {
	// Disease holds the value of the disease edge.
	Disease []*Disease
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DiseaseOrErr returns the Disease value or an error if the edge
// was not loaded in eager-loading.
func (e DiseaseTypeEdges) DiseaseOrErr() ([]*Disease, error) {
	if e.loadedTypes[0] {
		return e.Disease, nil
	}
	return nil, &NotLoadedError{edge: "disease"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiseaseType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiseaseType fields.
func (dt *DiseaseType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(diseasetype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	dt.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		dt.Name = value.String
	}
	return nil
}

// QueryDisease queries the disease edge of the DiseaseType.
func (dt *DiseaseType) QueryDisease() *DiseaseQuery {
	return (&DiseaseTypeClient{config: dt.config}).QueryDisease(dt)
}

// Update returns a builder for updating this DiseaseType.
// Note that, you need to call DiseaseType.Unwrap() before calling this method, if this DiseaseType
// was returned from a transaction, and the transaction was committed or rolled back.
func (dt *DiseaseType) Update() *DiseaseTypeUpdateOne {
	return (&DiseaseTypeClient{config: dt.config}).UpdateOne(dt)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (dt *DiseaseType) Unwrap() *DiseaseType {
	tx, ok := dt.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiseaseType is not a transactional entity")
	}
	dt.config.driver = tx.drv
	return dt
}

// String implements the fmt.Stringer.
func (dt *DiseaseType) String() string {
	var builder strings.Builder
	builder.WriteString("DiseaseType(")
	builder.WriteString(fmt.Sprintf("id=%v", dt.ID))
	builder.WriteString(", name=")
	builder.WriteString(dt.Name)
	builder.WriteByte(')')
	return builder.String()
}

// DiseaseTypes is a parsable slice of DiseaseType.
type DiseaseTypes []*DiseaseType

func (dt DiseaseTypes) config(cfg config) {
	for _i := range dt {
		dt[_i].config = cfg
	}
}
