// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"

	"github.com/KOB4k/app/ent/disease"
	"github.com/KOB4k/app/ent/diseasetype"
	"github.com/KOB4k/app/ent/employee"
	"github.com/KOB4k/app/ent/severity"

	"github.com/facebookincubator/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDisease     = "Disease"
	TypeDiseasetype = "Diseasetype"
	TypeEmployee    = "Employee"
	TypeSeverity    = "Severity"
)

// DiseaseMutation represents an operation that mutate the Diseases
// nodes in the graph.
type DiseaseMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	_Name              *string
	_Symptom           *string
	_Contagion         *string
	clearedFields      map[string]struct{}
	employee           *int
	clearedemployee    bool
	severity           *int
	clearedseverity    bool
	diseasetype        *int
	cleareddiseasetype bool
	done               bool
	oldValue           func(context.Context) (*Disease, error)
}

var _ ent.Mutation = (*DiseaseMutation)(nil)

// diseaseOption allows to manage the mutation configuration using functional options.
type diseaseOption func(*DiseaseMutation)

// newDiseaseMutation creates new mutation for $n.Name.
func newDiseaseMutation(c config, op Op, opts ...diseaseOption) *DiseaseMutation {
	m := &DiseaseMutation{
		config:        c,
		op:            op,
		typ:           TypeDisease,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDiseaseID sets the id field of the mutation.
func withDiseaseID(id int) diseaseOption {
	return func(m *DiseaseMutation) {
		var (
			err   error
			once  sync.Once
			value *Disease
		)
		m.oldValue = func(ctx context.Context) (*Disease, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Disease.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDisease sets the old Disease of the mutation.
func withDisease(node *Disease) diseaseOption {
	return func(m *DiseaseMutation) {
		m.oldValue = func(context.Context) (*Disease, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DiseaseMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DiseaseMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *DiseaseMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the Name field.
func (m *DiseaseMutation) SetName(s string) {
	m._Name = &s
}

// Name returns the Name value in the mutation.
func (m *DiseaseMutation) Name() (r string, exists bool) {
	v := m._Name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old Name value of the Disease.
// If the Disease object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *DiseaseMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName reset all changes of the "Name" field.
func (m *DiseaseMutation) ResetName() {
	m._Name = nil
}

// SetSymptom sets the Symptom field.
func (m *DiseaseMutation) SetSymptom(s string) {
	m._Symptom = &s
}

// Symptom returns the Symptom value in the mutation.
func (m *DiseaseMutation) Symptom() (r string, exists bool) {
	v := m._Symptom
	if v == nil {
		return
	}
	return *v, true
}

// OldSymptom returns the old Symptom value of the Disease.
// If the Disease object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *DiseaseMutation) OldSymptom(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldSymptom is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldSymptom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSymptom: %w", err)
	}
	return oldValue.Symptom, nil
}

// ResetSymptom reset all changes of the "Symptom" field.
func (m *DiseaseMutation) ResetSymptom() {
	m._Symptom = nil
}

// SetContagion sets the Contagion field.
func (m *DiseaseMutation) SetContagion(s string) {
	m._Contagion = &s
}

// Contagion returns the Contagion value in the mutation.
func (m *DiseaseMutation) Contagion() (r string, exists bool) {
	v := m._Contagion
	if v == nil {
		return
	}
	return *v, true
}

// OldContagion returns the old Contagion value of the Disease.
// If the Disease object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *DiseaseMutation) OldContagion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldContagion is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldContagion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContagion: %w", err)
	}
	return oldValue.Contagion, nil
}

// ResetContagion reset all changes of the "Contagion" field.
func (m *DiseaseMutation) ResetContagion() {
	m._Contagion = nil
}

// SetEmployeeID sets the employee edge to Employee by id.
func (m *DiseaseMutation) SetEmployeeID(id int) {
	m.employee = &id
}

// ClearEmployee clears the employee edge to Employee.
func (m *DiseaseMutation) ClearEmployee() {
	m.clearedemployee = true
}

// EmployeeCleared returns if the edge employee was cleared.
func (m *DiseaseMutation) EmployeeCleared() bool {
	return m.clearedemployee
}

// EmployeeID returns the employee id in the mutation.
func (m *DiseaseMutation) EmployeeID() (id int, exists bool) {
	if m.employee != nil {
		return *m.employee, true
	}
	return
}

// EmployeeIDs returns the employee ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// EmployeeID instead. It exists only for internal usage by the builders.
func (m *DiseaseMutation) EmployeeIDs() (ids []int) {
	if id := m.employee; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetEmployee reset all changes of the "employee" edge.
func (m *DiseaseMutation) ResetEmployee() {
	m.employee = nil
	m.clearedemployee = false
}

// SetSeverityID sets the severity edge to Severity by id.
func (m *DiseaseMutation) SetSeverityID(id int) {
	m.severity = &id
}

// ClearSeverity clears the severity edge to Severity.
func (m *DiseaseMutation) ClearSeverity() {
	m.clearedseverity = true
}

// SeverityCleared returns if the edge severity was cleared.
func (m *DiseaseMutation) SeverityCleared() bool {
	return m.clearedseverity
}

// SeverityID returns the severity id in the mutation.
func (m *DiseaseMutation) SeverityID() (id int, exists bool) {
	if m.severity != nil {
		return *m.severity, true
	}
	return
}

// SeverityIDs returns the severity ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// SeverityID instead. It exists only for internal usage by the builders.
func (m *DiseaseMutation) SeverityIDs() (ids []int) {
	if id := m.severity; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSeverity reset all changes of the "severity" edge.
func (m *DiseaseMutation) ResetSeverity() {
	m.severity = nil
	m.clearedseverity = false
}

// SetDiseasetypeID sets the diseasetype edge to Diseasetype by id.
func (m *DiseaseMutation) SetDiseasetypeID(id int) {
	m.diseasetype = &id
}

// ClearDiseasetype clears the diseasetype edge to Diseasetype.
func (m *DiseaseMutation) ClearDiseasetype() {
	m.cleareddiseasetype = true
}

// DiseasetypeCleared returns if the edge diseasetype was cleared.
func (m *DiseaseMutation) DiseasetypeCleared() bool {
	return m.cleareddiseasetype
}

// DiseasetypeID returns the diseasetype id in the mutation.
func (m *DiseaseMutation) DiseasetypeID() (id int, exists bool) {
	if m.diseasetype != nil {
		return *m.diseasetype, true
	}
	return
}

// DiseasetypeIDs returns the diseasetype ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// DiseasetypeID instead. It exists only for internal usage by the builders.
func (m *DiseaseMutation) DiseasetypeIDs() (ids []int) {
	if id := m.diseasetype; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDiseasetype reset all changes of the "diseasetype" edge.
func (m *DiseaseMutation) ResetDiseasetype() {
	m.diseasetype = nil
	m.cleareddiseasetype = false
}

// Op returns the operation name.
func (m *DiseaseMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Disease).
func (m *DiseaseMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *DiseaseMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m._Name != nil {
		fields = append(fields, disease.FieldName)
	}
	if m._Symptom != nil {
		fields = append(fields, disease.FieldSymptom)
	}
	if m._Contagion != nil {
		fields = append(fields, disease.FieldContagion)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *DiseaseMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case disease.FieldName:
		return m.Name()
	case disease.FieldSymptom:
		return m.Symptom()
	case disease.FieldContagion:
		return m.Contagion()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *DiseaseMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case disease.FieldName:
		return m.OldName(ctx)
	case disease.FieldSymptom:
		return m.OldSymptom(ctx)
	case disease.FieldContagion:
		return m.OldContagion(ctx)
	}
	return nil, fmt.Errorf("unknown Disease field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *DiseaseMutation) SetField(name string, value ent.Value) error {
	switch name {
	case disease.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case disease.FieldSymptom:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSymptom(v)
		return nil
	case disease.FieldContagion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContagion(v)
		return nil
	}
	return fmt.Errorf("unknown Disease field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *DiseaseMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *DiseaseMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *DiseaseMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Disease numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *DiseaseMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *DiseaseMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *DiseaseMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Disease nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *DiseaseMutation) ResetField(name string) error {
	switch name {
	case disease.FieldName:
		m.ResetName()
		return nil
	case disease.FieldSymptom:
		m.ResetSymptom()
		return nil
	case disease.FieldContagion:
		m.ResetContagion()
		return nil
	}
	return fmt.Errorf("unknown Disease field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *DiseaseMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.employee != nil {
		edges = append(edges, disease.EdgeEmployee)
	}
	if m.severity != nil {
		edges = append(edges, disease.EdgeSeverity)
	}
	if m.diseasetype != nil {
		edges = append(edges, disease.EdgeDiseasetype)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *DiseaseMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case disease.EdgeEmployee:
		if id := m.employee; id != nil {
			return []ent.Value{*id}
		}
	case disease.EdgeSeverity:
		if id := m.severity; id != nil {
			return []ent.Value{*id}
		}
	case disease.EdgeDiseasetype:
		if id := m.diseasetype; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *DiseaseMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *DiseaseMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *DiseaseMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedemployee {
		edges = append(edges, disease.EdgeEmployee)
	}
	if m.clearedseverity {
		edges = append(edges, disease.EdgeSeverity)
	}
	if m.cleareddiseasetype {
		edges = append(edges, disease.EdgeDiseasetype)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *DiseaseMutation) EdgeCleared(name string) bool {
	switch name {
	case disease.EdgeEmployee:
		return m.clearedemployee
	case disease.EdgeSeverity:
		return m.clearedseverity
	case disease.EdgeDiseasetype:
		return m.cleareddiseasetype
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *DiseaseMutation) ClearEdge(name string) error {
	switch name {
	case disease.EdgeEmployee:
		m.ClearEmployee()
		return nil
	case disease.EdgeSeverity:
		m.ClearSeverity()
		return nil
	case disease.EdgeDiseasetype:
		m.ClearDiseasetype()
		return nil
	}
	return fmt.Errorf("unknown Disease unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *DiseaseMutation) ResetEdge(name string) error {
	switch name {
	case disease.EdgeEmployee:
		m.ResetEmployee()
		return nil
	case disease.EdgeSeverity:
		m.ResetSeverity()
		return nil
	case disease.EdgeDiseasetype:
		m.ResetDiseasetype()
		return nil
	}
	return fmt.Errorf("unknown Disease edge %s", name)
}

// DiseasetypeMutation represents an operation that mutate the Diseasetypes
// nodes in the graph.
type DiseasetypeMutation struct {
	config
	op             Op
	typ            string
	id             *int
	_Name          *string
	clearedFields  map[string]struct{}
	disease        map[int]struct{}
	removeddisease map[int]struct{}
	done           bool
	oldValue       func(context.Context) (*Diseasetype, error)
}

var _ ent.Mutation = (*DiseasetypeMutation)(nil)

// diseasetypeOption allows to manage the mutation configuration using functional options.
type diseasetypeOption func(*DiseasetypeMutation)

// newDiseasetypeMutation creates new mutation for $n.Name.
func newDiseasetypeMutation(c config, op Op, opts ...diseasetypeOption) *DiseasetypeMutation {
	m := &DiseasetypeMutation{
		config:        c,
		op:            op,
		typ:           TypeDiseasetype,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDiseasetypeID sets the id field of the mutation.
func withDiseasetypeID(id int) diseasetypeOption {
	return func(m *DiseasetypeMutation) {
		var (
			err   error
			once  sync.Once
			value *Diseasetype
		)
		m.oldValue = func(ctx context.Context) (*Diseasetype, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Diseasetype.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDiseasetype sets the old Diseasetype of the mutation.
func withDiseasetype(node *Diseasetype) diseasetypeOption {
	return func(m *DiseasetypeMutation) {
		m.oldValue = func(context.Context) (*Diseasetype, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DiseasetypeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DiseasetypeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *DiseasetypeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the Name field.
func (m *DiseasetypeMutation) SetName(s string) {
	m._Name = &s
}

// Name returns the Name value in the mutation.
func (m *DiseasetypeMutation) Name() (r string, exists bool) {
	v := m._Name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old Name value of the Diseasetype.
// If the Diseasetype object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *DiseasetypeMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName reset all changes of the "Name" field.
func (m *DiseasetypeMutation) ResetName() {
	m._Name = nil
}

// AddDiseaseIDs adds the disease edge to Disease by ids.
func (m *DiseasetypeMutation) AddDiseaseIDs(ids ...int) {
	if m.disease == nil {
		m.disease = make(map[int]struct{})
	}
	for i := range ids {
		m.disease[ids[i]] = struct{}{}
	}
}

// RemoveDiseaseIDs removes the disease edge to Disease by ids.
func (m *DiseasetypeMutation) RemoveDiseaseIDs(ids ...int) {
	if m.removeddisease == nil {
		m.removeddisease = make(map[int]struct{})
	}
	for i := range ids {
		m.removeddisease[ids[i]] = struct{}{}
	}
}

// RemovedDisease returns the removed ids of disease.
func (m *DiseasetypeMutation) RemovedDiseaseIDs() (ids []int) {
	for id := range m.removeddisease {
		ids = append(ids, id)
	}
	return
}

// DiseaseIDs returns the disease ids in the mutation.
func (m *DiseasetypeMutation) DiseaseIDs() (ids []int) {
	for id := range m.disease {
		ids = append(ids, id)
	}
	return
}

// ResetDisease reset all changes of the "disease" edge.
func (m *DiseasetypeMutation) ResetDisease() {
	m.disease = nil
	m.removeddisease = nil
}

// Op returns the operation name.
func (m *DiseasetypeMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Diseasetype).
func (m *DiseasetypeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *DiseasetypeMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m._Name != nil {
		fields = append(fields, diseasetype.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *DiseasetypeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case diseasetype.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *DiseasetypeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case diseasetype.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Diseasetype field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *DiseasetypeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case diseasetype.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Diseasetype field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *DiseasetypeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *DiseasetypeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *DiseasetypeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Diseasetype numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *DiseasetypeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *DiseasetypeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *DiseasetypeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Diseasetype nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *DiseasetypeMutation) ResetField(name string) error {
	switch name {
	case diseasetype.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Diseasetype field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *DiseasetypeMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.disease != nil {
		edges = append(edges, diseasetype.EdgeDisease)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *DiseasetypeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case diseasetype.EdgeDisease:
		ids := make([]ent.Value, 0, len(m.disease))
		for id := range m.disease {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *DiseasetypeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removeddisease != nil {
		edges = append(edges, diseasetype.EdgeDisease)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *DiseasetypeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case diseasetype.EdgeDisease:
		ids := make([]ent.Value, 0, len(m.removeddisease))
		for id := range m.removeddisease {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *DiseasetypeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *DiseasetypeMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *DiseasetypeMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Diseasetype unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *DiseasetypeMutation) ResetEdge(name string) error {
	switch name {
	case diseasetype.EdgeDisease:
		m.ResetDisease()
		return nil
	}
	return fmt.Errorf("unknown Diseasetype edge %s", name)
}

// EmployeeMutation represents an operation that mutate the Employees
// nodes in the graph.
type EmployeeMutation struct {
	config
	op             Op
	typ            string
	id             *int
	_User_id       *string
	clearedFields  map[string]struct{}
	disease        map[int]struct{}
	removeddisease map[int]struct{}
	done           bool
	oldValue       func(context.Context) (*Employee, error)
}

var _ ent.Mutation = (*EmployeeMutation)(nil)

// employeeOption allows to manage the mutation configuration using functional options.
type employeeOption func(*EmployeeMutation)

// newEmployeeMutation creates new mutation for $n.Name.
func newEmployeeMutation(c config, op Op, opts ...employeeOption) *EmployeeMutation {
	m := &EmployeeMutation{
		config:        c,
		op:            op,
		typ:           TypeEmployee,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEmployeeID sets the id field of the mutation.
func withEmployeeID(id int) employeeOption {
	return func(m *EmployeeMutation) {
		var (
			err   error
			once  sync.Once
			value *Employee
		)
		m.oldValue = func(ctx context.Context) (*Employee, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Employee.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEmployee sets the old Employee of the mutation.
func withEmployee(node *Employee) employeeOption {
	return func(m *EmployeeMutation) {
		m.oldValue = func(context.Context) (*Employee, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EmployeeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EmployeeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *EmployeeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetUserID sets the User_id field.
func (m *EmployeeMutation) SetUserID(s string) {
	m._User_id = &s
}

// UserID returns the User_id value in the mutation.
func (m *EmployeeMutation) UserID() (r string, exists bool) {
	v := m._User_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old User_id value of the Employee.
// If the Employee object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *EmployeeMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUserID is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID reset all changes of the "User_id" field.
func (m *EmployeeMutation) ResetUserID() {
	m._User_id = nil
}

// AddDiseaseIDs adds the disease edge to Disease by ids.
func (m *EmployeeMutation) AddDiseaseIDs(ids ...int) {
	if m.disease == nil {
		m.disease = make(map[int]struct{})
	}
	for i := range ids {
		m.disease[ids[i]] = struct{}{}
	}
}

// RemoveDiseaseIDs removes the disease edge to Disease by ids.
func (m *EmployeeMutation) RemoveDiseaseIDs(ids ...int) {
	if m.removeddisease == nil {
		m.removeddisease = make(map[int]struct{})
	}
	for i := range ids {
		m.removeddisease[ids[i]] = struct{}{}
	}
}

// RemovedDisease returns the removed ids of disease.
func (m *EmployeeMutation) RemovedDiseaseIDs() (ids []int) {
	for id := range m.removeddisease {
		ids = append(ids, id)
	}
	return
}

// DiseaseIDs returns the disease ids in the mutation.
func (m *EmployeeMutation) DiseaseIDs() (ids []int) {
	for id := range m.disease {
		ids = append(ids, id)
	}
	return
}

// ResetDisease reset all changes of the "disease" edge.
func (m *EmployeeMutation) ResetDisease() {
	m.disease = nil
	m.removeddisease = nil
}

// Op returns the operation name.
func (m *EmployeeMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Employee).
func (m *EmployeeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *EmployeeMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m._User_id != nil {
		fields = append(fields, employee.FieldUserID)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *EmployeeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case employee.FieldUserID:
		return m.UserID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *EmployeeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case employee.FieldUserID:
		return m.OldUserID(ctx)
	}
	return nil, fmt.Errorf("unknown Employee field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *EmployeeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case employee.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	}
	return fmt.Errorf("unknown Employee field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *EmployeeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *EmployeeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *EmployeeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Employee numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *EmployeeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *EmployeeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *EmployeeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Employee nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *EmployeeMutation) ResetField(name string) error {
	switch name {
	case employee.FieldUserID:
		m.ResetUserID()
		return nil
	}
	return fmt.Errorf("unknown Employee field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *EmployeeMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.disease != nil {
		edges = append(edges, employee.EdgeDisease)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *EmployeeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case employee.EdgeDisease:
		ids := make([]ent.Value, 0, len(m.disease))
		for id := range m.disease {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *EmployeeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removeddisease != nil {
		edges = append(edges, employee.EdgeDisease)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *EmployeeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case employee.EdgeDisease:
		ids := make([]ent.Value, 0, len(m.removeddisease))
		for id := range m.removeddisease {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *EmployeeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *EmployeeMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *EmployeeMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Employee unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *EmployeeMutation) ResetEdge(name string) error {
	switch name {
	case employee.EdgeDisease:
		m.ResetDisease()
		return nil
	}
	return fmt.Errorf("unknown Employee edge %s", name)
}

// SeverityMutation represents an operation that mutate the Severities
// nodes in the graph.
type SeverityMutation struct {
	config
	op             Op
	typ            string
	id             *int
	_Name          *string
	clearedFields  map[string]struct{}
	disease        map[int]struct{}
	removeddisease map[int]struct{}
	done           bool
	oldValue       func(context.Context) (*Severity, error)
}

var _ ent.Mutation = (*SeverityMutation)(nil)

// severityOption allows to manage the mutation configuration using functional options.
type severityOption func(*SeverityMutation)

// newSeverityMutation creates new mutation for $n.Name.
func newSeverityMutation(c config, op Op, opts ...severityOption) *SeverityMutation {
	m := &SeverityMutation{
		config:        c,
		op:            op,
		typ:           TypeSeverity,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSeverityID sets the id field of the mutation.
func withSeverityID(id int) severityOption {
	return func(m *SeverityMutation) {
		var (
			err   error
			once  sync.Once
			value *Severity
		)
		m.oldValue = func(ctx context.Context) (*Severity, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Severity.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSeverity sets the old Severity of the mutation.
func withSeverity(node *Severity) severityOption {
	return func(m *SeverityMutation) {
		m.oldValue = func(context.Context) (*Severity, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SeverityMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SeverityMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *SeverityMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the Name field.
func (m *SeverityMutation) SetName(s string) {
	m._Name = &s
}

// Name returns the Name value in the mutation.
func (m *SeverityMutation) Name() (r string, exists bool) {
	v := m._Name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old Name value of the Severity.
// If the Severity object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *SeverityMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName reset all changes of the "Name" field.
func (m *SeverityMutation) ResetName() {
	m._Name = nil
}

// AddDiseaseIDs adds the disease edge to Disease by ids.
func (m *SeverityMutation) AddDiseaseIDs(ids ...int) {
	if m.disease == nil {
		m.disease = make(map[int]struct{})
	}
	for i := range ids {
		m.disease[ids[i]] = struct{}{}
	}
}

// RemoveDiseaseIDs removes the disease edge to Disease by ids.
func (m *SeverityMutation) RemoveDiseaseIDs(ids ...int) {
	if m.removeddisease == nil {
		m.removeddisease = make(map[int]struct{})
	}
	for i := range ids {
		m.removeddisease[ids[i]] = struct{}{}
	}
}

// RemovedDisease returns the removed ids of disease.
func (m *SeverityMutation) RemovedDiseaseIDs() (ids []int) {
	for id := range m.removeddisease {
		ids = append(ids, id)
	}
	return
}

// DiseaseIDs returns the disease ids in the mutation.
func (m *SeverityMutation) DiseaseIDs() (ids []int) {
	for id := range m.disease {
		ids = append(ids, id)
	}
	return
}

// ResetDisease reset all changes of the "disease" edge.
func (m *SeverityMutation) ResetDisease() {
	m.disease = nil
	m.removeddisease = nil
}

// Op returns the operation name.
func (m *SeverityMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Severity).
func (m *SeverityMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *SeverityMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m._Name != nil {
		fields = append(fields, severity.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *SeverityMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case severity.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *SeverityMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case severity.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Severity field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *SeverityMutation) SetField(name string, value ent.Value) error {
	switch name {
	case severity.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Severity field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *SeverityMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *SeverityMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *SeverityMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Severity numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *SeverityMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *SeverityMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *SeverityMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Severity nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *SeverityMutation) ResetField(name string) error {
	switch name {
	case severity.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Severity field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *SeverityMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.disease != nil {
		edges = append(edges, severity.EdgeDisease)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *SeverityMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case severity.EdgeDisease:
		ids := make([]ent.Value, 0, len(m.disease))
		for id := range m.disease {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *SeverityMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removeddisease != nil {
		edges = append(edges, severity.EdgeDisease)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *SeverityMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case severity.EdgeDisease:
		ids := make([]ent.Value, 0, len(m.removeddisease))
		for id := range m.removeddisease {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *SeverityMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *SeverityMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *SeverityMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Severity unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *SeverityMutation) ResetEdge(name string) error {
	switch name {
	case severity.EdgeDisease:
		m.ResetDisease()
		return nil
	}
	return fmt.Errorf("unknown Severity edge %s", name)
}
