// Code generated by entc, DO NOT EDIT.

package severity

const (
	// Label holds the string label denoting the severity type in the database.
	Label = "severity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeDisease holds the string denoting the disease edge name in mutations.
	EdgeDisease = "disease"

	// Table holds the table name of the severity in the database.
	Table = "severities"
	// DiseaseTable is the table the holds the disease relation/edge.
	DiseaseTable = "diseases"
	// DiseaseInverseTable is the table name for the Disease entity.
	// It exists in this package in order to avoid circular dependency with the "disease" package.
	DiseaseInverseTable = "diseases"
	// DiseaseColumn is the table column denoting the disease relation/edge.
	DiseaseColumn = "severity_disease"
)

// Columns holds all SQL columns for severity fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
