/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDiseasetypeEdges,
    EntDiseasetypeEdgesFromJSON,
    EntDiseasetypeEdgesFromJSONTyped,
    EntDiseasetypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDiseasetype
 */
export interface EntDiseasetype {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntDiseasetype
     */
    name?: string;
    /**
     * 
     * @type {EntDiseasetypeEdges}
     * @memberof EntDiseasetype
     */
    edges?: EntDiseasetypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDiseasetype
     */
    id?: number;
}

export function EntDiseasetypeFromJSON(json: any): EntDiseasetype {
    return EntDiseasetypeFromJSONTyped(json, false);
}

export function EntDiseasetypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDiseasetype {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntDiseasetypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDiseasetypeToJSON(value?: EntDiseasetype | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntDiseasetypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


