/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDiseasetype,
    EntDiseasetypeFromJSON,
    EntDiseasetypeFromJSONTyped,
    EntDiseasetypeToJSON,
    EntEmployee,
    EntEmployeeFromJSON,
    EntEmployeeFromJSONTyped,
    EntEmployeeToJSON,
    EntSeverity,
    EntSeverityFromJSON,
    EntSeverityFromJSONTyped,
    EntSeverityToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDiseaseEdges
 */
export interface EntDiseaseEdges {
    /**
     * 
     * @type {EntDiseasetype}
     * @memberof EntDiseaseEdges
     */
    diseasetype?: EntDiseasetype;
    /**
     * 
     * @type {EntEmployee}
     * @memberof EntDiseaseEdges
     */
    employee?: EntEmployee;
    /**
     * 
     * @type {EntSeverity}
     * @memberof EntDiseaseEdges
     */
    serverity?: EntSeverity;
}

export function EntDiseaseEdgesFromJSON(json: any): EntDiseaseEdges {
    return EntDiseaseEdgesFromJSONTyped(json, false);
}

export function EntDiseaseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDiseaseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'diseasetype': !exists(json, 'diseasetype') ? undefined : EntDiseasetypeFromJSON(json['diseasetype']),
        'employee': !exists(json, 'employee') ? undefined : EntEmployeeFromJSON(json['employee']),
        'serverity': !exists(json, 'serverity') ? undefined : EntSeverityFromJSON(json['serverity']),
    };
}

export function EntDiseaseEdgesToJSON(value?: EntDiseaseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'diseasetype': EntDiseasetypeToJSON(value.diseasetype),
        'employee': EntEmployeeToJSON(value.employee),
        'serverity': EntSeverityToJSON(value.serverity),
    };
}


