// Code generated by entc, DO NOT EDIT.

package disease

import (
	"github.com/KOB4k/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Syptom applies equality check predicate on the "syptom" field. It's identical to SyptomEQ.
func Syptom(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSyptom), v))
	})
}

// Contagion applies equality check predicate on the "contagion" field. It's identical to ContagionEQ.
func Contagion(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContagion), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Disease {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Disease {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// SyptomEQ applies the EQ predicate on the "syptom" field.
func SyptomEQ(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSyptom), v))
	})
}

// SyptomNEQ applies the NEQ predicate on the "syptom" field.
func SyptomNEQ(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSyptom), v))
	})
}

// SyptomIn applies the In predicate on the "syptom" field.
func SyptomIn(vs ...string) predicate.Disease {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSyptom), v...))
	})
}

// SyptomNotIn applies the NotIn predicate on the "syptom" field.
func SyptomNotIn(vs ...string) predicate.Disease {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSyptom), v...))
	})
}

// SyptomGT applies the GT predicate on the "syptom" field.
func SyptomGT(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSyptom), v))
	})
}

// SyptomGTE applies the GTE predicate on the "syptom" field.
func SyptomGTE(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSyptom), v))
	})
}

// SyptomLT applies the LT predicate on the "syptom" field.
func SyptomLT(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSyptom), v))
	})
}

// SyptomLTE applies the LTE predicate on the "syptom" field.
func SyptomLTE(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSyptom), v))
	})
}

// SyptomContains applies the Contains predicate on the "syptom" field.
func SyptomContains(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSyptom), v))
	})
}

// SyptomHasPrefix applies the HasPrefix predicate on the "syptom" field.
func SyptomHasPrefix(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSyptom), v))
	})
}

// SyptomHasSuffix applies the HasSuffix predicate on the "syptom" field.
func SyptomHasSuffix(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSyptom), v))
	})
}

// SyptomEqualFold applies the EqualFold predicate on the "syptom" field.
func SyptomEqualFold(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSyptom), v))
	})
}

// SyptomContainsFold applies the ContainsFold predicate on the "syptom" field.
func SyptomContainsFold(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSyptom), v))
	})
}

// ContagionEQ applies the EQ predicate on the "contagion" field.
func ContagionEQ(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContagion), v))
	})
}

// ContagionNEQ applies the NEQ predicate on the "contagion" field.
func ContagionNEQ(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldContagion), v))
	})
}

// ContagionIn applies the In predicate on the "contagion" field.
func ContagionIn(vs ...string) predicate.Disease {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldContagion), v...))
	})
}

// ContagionNotIn applies the NotIn predicate on the "contagion" field.
func ContagionNotIn(vs ...string) predicate.Disease {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Disease(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldContagion), v...))
	})
}

// ContagionGT applies the GT predicate on the "contagion" field.
func ContagionGT(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldContagion), v))
	})
}

// ContagionGTE applies the GTE predicate on the "contagion" field.
func ContagionGTE(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldContagion), v))
	})
}

// ContagionLT applies the LT predicate on the "contagion" field.
func ContagionLT(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldContagion), v))
	})
}

// ContagionLTE applies the LTE predicate on the "contagion" field.
func ContagionLTE(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldContagion), v))
	})
}

// ContagionContains applies the Contains predicate on the "contagion" field.
func ContagionContains(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldContagion), v))
	})
}

// ContagionHasPrefix applies the HasPrefix predicate on the "contagion" field.
func ContagionHasPrefix(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldContagion), v))
	})
}

// ContagionHasSuffix applies the HasSuffix predicate on the "contagion" field.
func ContagionHasSuffix(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldContagion), v))
	})
}

// ContagionEqualFold applies the EqualFold predicate on the "contagion" field.
func ContagionEqualFold(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldContagion), v))
	})
}

// ContagionContainsFold applies the ContainsFold predicate on the "contagion" field.
func ContagionContainsFold(v string) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldContagion), v))
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasServerity applies the HasEdge predicate on the "serverity" edge.
func HasServerity() predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ServerityTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerityTable, ServerityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerityWith applies the HasEdge predicate on the "serverity" edge with a given conditions (other predicates).
func HasServerityWith(preds ...predicate.Severity) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ServerityInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServerityTable, ServerityColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDiseasetype applies the HasEdge predicate on the "diseasetype" edge.
func HasDiseasetype() predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DiseasetypeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DiseasetypeTable, DiseasetypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDiseasetypeWith applies the HasEdge predicate on the "diseasetype" edge with a given conditions (other predicates).
func HasDiseasetypeWith(preds ...predicate.DiseaseType) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DiseasetypeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DiseasetypeTable, DiseasetypeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Disease) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Disease) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Disease) predicate.Disease {
	return predicate.Disease(func(s *sql.Selector) {
		p(s.Not())
	})
}
